### ISSUE TITLE
Keeping receipts

### ISSUE THREAD

**Issue by tracykteal** [datacarpentry/policies#2]
NumFOCUS policy on retaining receipts is that electronic copies of the receipts must be kept on file for 7 years. We do not need to keep physical receipts. 

Potentially add this information to the reimbursement policy.

Also, let staff know about the policy.

**Comment by kariljordan** [comment]
Hi @tracykteal, is it okay for me to close this issue as we've merged and the reimbursement policy is now located in our [handbook](https://docs.carpentries.org/topic_folders/policies/reimbursement-policy.html)?

**Comment by tracykteal** [comment]
Yes, it can be closed, as it's also not relevant anymore since it's not NumFOCUS policies that are relevant.
